### ISSUE TITLE
`truffle unbox` throws ERR_CHILD_PROCESS_STDIO_MAXBUFFER

### ISSUE THREAD

**Issue by elifarley** [chuckbergeron/etherplate#17]
I've 
```
[nft-test]$ truffle version
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)

[nft-test]$ truffle unbox chuckbergeron/etherplate
Downloading...
Unpacking...
Setting up...
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at Socket.onChildStderr (child_process.js:365:14)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:145:17)
```

**Comment by chuckbergeron** [comment]
@elifarley Thanks for opening this. I just gave it a shot on my Macbook Pro (fresh install, `truffle unbox`) and it worked without issues. Here's my env:

`node -v`
v8.11.4
`npm -v`
5.6.0
